### ISSUE TITLE
Add Handlers for ISS / QAS

### ISSUE THREAD

**Issue by MikeHart85** [NSLS-II/nsls2-detector-handlers#2]
ISS and QAS both have Pizzabox handlers with conflicting IDs and implementations, which need to be added to this repo and ideally merged into one class which is capable of handling both.

**Comment by MikeHart85** [comment]
ISS handlers: https://github.com/NSLS-II-ISS/profile_collection/blob/master/startup/10-detectors.py#L753-L839

QAS handlers: https://github.com/NSLS-II-QAS/profile_collection/blob/master/startup/11-handlers.py#L15-L112

**Comment by mrakitin** [comment]
Resolved via #3.
